// Writes src/icons.js: the Feather glyphs the video draws, as inline SVG
// strings. Feather is the app's own icon set (@expo/vector-icons Feather), so
// the phone screens show the same glyphs the real app does.
import { readFileSync, writeFileSync } from 'node:fs';

const icons = JSON.parse(readFileSync(new URL('../node_modules/feather-icons/dist/icons.json', import.meta.url)));
const NEEDED = [
  'search', 'mic', 'bell', 'home', 'upload', 'camera', 'folder', 'image', 'info', 'file-text',
  'check-circle', 'check', 'cpu', 'send', 'arrow-left', 'plus', 'users', 'user-plus', 'clock',
  'volume-2', 'square', 'shield', 'lock', 'layers', 'message-circle', 'refresh-cw', 'mail',
  'alert-circle', 'phone', 'phone-missed', 'phone-off', 'wifi', 'battery', 'x', 'key', 'inbox',
  'paperclip', 'more-vertical', 'chevron-right', 'smartphone', 'eye-off', 'heart', 'zap',
  // v4 screens: drawer, family tree, emergency card, reminders, Gmail import, saved chats
  'git-branch', 'plus-square', 'settings', 'log-out', 'chevron-down', 'check-square', 'droplet',
  'alert-triangle', 'edit-2', 'maximize-2', 'calendar', 'gift', 'bookmark', 'star', 'link',
];
const missing = NEEDED.filter(n => !icons[n]);
if (missing.length) throw new Error(`Unknown Feather icons: ${missing.join(', ')}`);

const body = NEEDED.map(n => `  '${n}': '${icons[n].replace(/'/g, "\\'")}',`).join('\n');
writeFileSync(new URL('../src/icons.js', import.meta.url), `// Generated by tools/build-icons.mjs from feather-icons. Do not edit.
const FEATHER = {
${body}
};

/** An inline Feather icon, sized and coloured like @expo/vector-icons' <Feather>. */
export function icon(name, size = 24, color = 'currentColor', strokeWidth = 2) {
  const inner = FEATHER[name];
  if (!inner) throw new Error('Unknown icon ' + name);
  return '<svg class="fi fi-' + name + '" xmlns="http://www.w3.org/2000/svg" width="' + size + '" height="' + size +
    '" viewBox="0 0 24 24" fill="none" stroke="' + color + '" stroke-width="' + strokeWidth +
    '" stroke-linecap="round" stroke-linejoin="round">' + inner + '</svg>';
}
`);
console.log(`icons.js: ${NEEDED.length} icons`);
